-- Snapshot of the tables that already exist in the ata-crm D1 database (created by the
-- separate "ata-crm" Worker and filled from QuickBooks). ALREADY APPLIED — do not run in
-- production. Kept so tests run against the real layout.

CREATE TABLE customers (id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT NOT NULL, company TEXT, email TEXT, phone TEXT, address TEXT, city TEXT, state TEXT, zip TEXT, type TEXT DEFAULT 'residential', status TEXT DEFAULT 'active', source TEXT, notes TEXT, qb_id TEXT, lifetime_value REAL DEFAULT 0, created_at TEXT DEFAULT (datetime('now')), updated_at TEXT DEFAULT (datetime('now')));
CREATE TABLE properties (id INTEGER PRIMARY KEY AUTOINCREMENT, customer_id INTEGER NOT NULL REFERENCES customers(id) ON DELETE CASCADE, label TEXT, address TEXT, city TEXT, state TEXT DEFAULT 'FL', zip TEXT, notes TEXT, created_at TEXT DEFAULT (datetime('now')));
CREATE TABLE jobs (id INTEGER PRIMARY KEY AUTOINCREMENT, customer_id INTEGER NOT NULL REFERENCES customers(id) ON DELETE CASCADE, property_id INTEGER REFERENCES properties(id), title TEXT NOT NULL, stage TEXT DEFAULT 'lead', value REAL DEFAULT 0, description TEXT, trade TEXT, start_date TEXT, end_date TEXT, next_action TEXT, next_action_date TEXT, created_at TEXT DEFAULT (datetime('now')), updated_at TEXT DEFAULT (datetime('now')));
CREATE TABLE activity (id INTEGER PRIMARY KEY AUTOINCREMENT, customer_id INTEGER REFERENCES customers(id) ON DELETE CASCADE, job_id INTEGER REFERENCES jobs(id), date TEXT DEFAULT (datetime('now')), type TEXT DEFAULT 'note', subject TEXT, body TEXT, created_at TEXT DEFAULT (datetime('now')));
CREATE TABLE estimates (id INTEGER PRIMARY KEY AUTOINCREMENT, customer_id INTEGER REFERENCES customers(id) ON DELETE CASCADE, job_id INTEGER REFERENCES jobs(id), number TEXT, date TEXT, expires TEXT, amount REAL DEFAULT 0, deposit REAL DEFAULT 0, status TEXT DEFAULT 'pending', accepted_date TEXT, notes TEXT, pdf_path TEXT, qb_id TEXT, qb_link TEXT, created_at TEXT DEFAULT (datetime('now')), updated_at TEXT DEFAULT (datetime('now')));
CREATE TABLE estimate_lines (id INTEGER PRIMARY KEY AUTOINCREMENT, estimate_id INTEGER NOT NULL REFERENCES estimates(id) ON DELETE CASCADE, kind TEXT DEFAULT 'labor', description TEXT, qty REAL DEFAULT 1, rate REAL DEFAULT 0, amount REAL DEFAULT 0, sort_order INTEGER DEFAULT 0);
CREATE TABLE invoices (id INTEGER PRIMARY KEY AUTOINCREMENT, customer_id INTEGER REFERENCES customers(id) ON DELETE CASCADE, job_id INTEGER REFERENCES jobs(id), estimate_id INTEGER REFERENCES estimates(id), number TEXT, date TEXT, due_date TEXT, project_address TEXT, amount REAL DEFAULT 0, balance REAL DEFAULT 0, deposit_paid REAL DEFAULT 0, status TEXT DEFAULT 'unpaid', payment_methods TEXT DEFAULT 'Check, Zelle, or Cash', reference_estimate TEXT, notes TEXT, pdf_path TEXT, qb_id TEXT, qb_link TEXT, created_at TEXT DEFAULT (datetime('now')), updated_at TEXT DEFAULT (datetime('now')));
CREATE TABLE invoice_lines (id INTEGER PRIMARY KEY AUTOINCREMENT, invoice_id INTEGER NOT NULL REFERENCES invoices(id) ON DELETE CASCADE, kind TEXT DEFAULT 'labor', description TEXT, qty REAL DEFAULT 1, rate REAL DEFAULT 0, amount REAL DEFAULT 0, sort_order INTEGER DEFAULT 0);
CREATE TABLE payments (id INTEGER PRIMARY KEY AUTOINCREMENT, invoice_id INTEGER REFERENCES invoices(id) ON DELETE CASCADE, customer_id INTEGER REFERENCES customers(id), date TEXT, amount REAL DEFAULT 0, method TEXT, notes TEXT, created_at TEXT DEFAULT (datetime('now')));
CREATE TABLE contracts (id INTEGER PRIMARY KEY AUTOINCREMENT, customer_id INTEGER REFERENCES customers(id) ON DELETE CASCADE, job_id INTEGER REFERENCES jobs(id), estimate_id INTEGER REFERENCES estimates(id), number TEXT, date TEXT, amount REAL DEFAULT 0, down_payment REAL DEFAULT 0, status TEXT DEFAULT 'draft', signed_date TEXT, pdf_path TEXT, notes TEXT, created_at TEXT DEFAULT (datetime('now')));
CREATE TABLE documents (id INTEGER PRIMARY KEY AUTOINCREMENT, customer_id INTEGER REFERENCES customers(id) ON DELETE CASCADE, job_id INTEGER REFERENCES jobs(id), kind TEXT, name TEXT, path TEXT, url TEXT, created_at TEXT DEFAULT (datetime('now')));
CREATE TABLE settings (key TEXT PRIMARY KEY, value TEXT);
CREATE TABLE users (id INTEGER PRIMARY KEY AUTOINCREMENT, email TEXT UNIQUE NOT NULL, name TEXT, password_hash TEXT NOT NULL, role TEXT DEFAULT 'owner', created_at TEXT DEFAULT (datetime('now')));
CREATE TABLE sessions (token TEXT PRIMARY KEY, user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE, expires_at TEXT NOT NULL, created_at TEXT DEFAULT (datetime('now')));
