import type { Service } from "./site";
import { lutronPhone, teslaPhone } from "./site-config";

const helpLineCallout = {
  eyebrow: "Lutron Help Line · 24/7",
  heading: "Already have a Lutron system? We answer the phone around the clock.",
  copy: `Anyone with a Lutron system can call ${lutronPhone.display}—no matter who installed it. If the fix needs a visit, we schedule a service call.`,
  href: "/lutron-help-line",
  link: "About the help line",
};

export const services: Record<string, Service> = {
  lighting: {
    path: "/services/lighting",
    metaTitle: "Lutron RadioRA 3 Lighting Control | Sarasota Dealer",
    metaDescription: "Whole-home scenes, keypads, dimming and shades with Lutron RadioRA 3 and Caséta, designed and installed by a Sarasota RadioRA 3 dealer.",
    eyebrow: "Lutron RadioRA 3 · Caséta",
    title: "Lighting that changes",
    italic: "how the home feels.",
    intro: "Refined dimming, architectural keypads, scenes, schedules, and shades—designed as one dependable whole-home system by a Lutron RadioRA 3 dealer.",
    image: "svc-lighting-hero",
    statement: "The best lighting control is felt in every room and barely noticed on the wall.",
    details: [
      { title: "Whole-home scenes", copy: "One touch can prepare the home for morning, entertaining, movie night, or bedtime without adjusting individual lights." },
      { title: "Architectural controls", copy: "Elegant keypads replace banks of switches and give every button a clear, intentional purpose." },
      { title: "Reliable performance", copy: "RadioRA 3 is built for dependable control throughout the home—not dependent on a collection of Wi-Fi bulbs." },
      { title: "Shades and schedules", copy: "Natural light, privacy, and energy use can work together through automated shades and time-based routines." },
    ],
    ideal: ["New construction and major remodels", "Homes with too many switches", "Clients who value design and simplicity", "Projects needing shades, scenes, or remote access"],
    phone: lutronPhone,
    callout: helpLineCallout,
    // Answers pending Jorge's approval; a question is published only once its answer is filled in.
    faqs: [
      { q: "Do I need to rewire for RadioRA 3?", a: "" },
      { q: "Can it control my existing fans and shades?", a: "" },
      { q: "What's the difference from Caséta?", a: "" },
      { q: "Can I add rooms later?", a: "" },
    ],
  },
  automation: {
    path: "/services/automation",
    metaTitle: "Whole-Home Control & Automation | Sarasota",
    metaDescription: "One simple way to run lighting, shades, climate, audio and security—built on Lutron RadioRA 3 and planned as one system for Gulf Coast homes.",
    eyebrow: "Whole-home control",
    title: "One home.",
    italic: "One experience.",
    intro: "Lighting, shades, climate, entertainment, and security brought together—built on Lutron RadioRA 3 and an interface the whole household can understand.",
    image: "svc-automation-hero",
    statement: "Automation should remove friction from daily life—not introduce another complicated app.",
    details: [
      { title: "Unified control", copy: "Manage the systems that matter from keypads, an app, or voice—with the wall controls still working the way people expect." },
      { title: "Personalized scenes", copy: "Create routines around how the home is actually used, from arrival and entertaining to sleep and travel." },
      { title: "Entertainment", copy: "Simplify televisions, streaming sources, music, and rooms so enjoying them does not require a lesson." },
      { title: "Professional support", copy: "The system is designed, programmed, documented, and supported by one accountable team." },
    ],
    ideal: ["Whole-home renovations", "New construction", "Multiple entertainment spaces", "Owners tired of disconnected apps"],
    phone: lutronPhone,
  },
  security: {
    path: "/services/security",
    metaTitle: "UniFi Protect Camera Systems | Sarasota & Bradenton",
    metaDescription: "Planned camera coverage, local recording and no monthly camera fees. Professional UniFi Protect design and installation in Sarasota and Bradenton.",
    eyebrow: "UniFi Protect",
    title: "Security that knows",
    italic: "what it sees.",
    intro: "Intentional camera coverage, intelligent detection, local recording, and secure remote access without monthly camera licensing fees.",
    image: "svc-security-hero",
    statement: "A camera system should help you find the moment that matters—not leave you searching through hours of footage.",
    details: [
      { title: "Planned coverage", copy: "Camera locations and lens choices are selected around entrances, approaches, blind spots, and identification goals." },
      { title: "Smart detection", copy: "Compatible cameras can distinguish people, vehicles, and other events for more useful alerts and faster review." },
      { title: "Local recording", copy: "Footage remains under your control on dedicated local hardware with secure remote access." },
      { title: "One ecosystem", copy: "Cameras, door access, networking, and related infrastructure can share one professionally managed platform." },
    ],
    ideal: ["Homes needing real perimeter coverage", "Small businesses and offices", "Multi-site properties", "Clients replacing consumer cameras"],
    // Answers pending Jorge's approval; a question is published only once its answer is filled in.
    faqs: [
      { q: "Do UniFi cameras have monthly fees?", a: "" },
      { q: "How long is footage kept?", a: "" },
      { q: "Can I see cameras from my phone?", a: "" },
      { q: "Can you replace my Ring cameras?", a: "" },
    ],
  },
  audio: {
    path: "/services/audio-video",
    metaTitle: "Whole-Home Audio & TV Installation | Sarasota",
    metaDescription: "Discreet speakers, outdoor audio and clean TV installs for indoor-outdoor Florida living, planned and installed by one Sarasota team.",
    eyebrow: "Whole-home audio & video",
    title: "Every room.",
    italic: "The right atmosphere.",
    intro: "Discreet speakers, simple television control, and music that moves naturally through the home—inside and out.",
    image: "svc-audio-video-hero",
    statement: "Great audio belongs in the architecture, not scattered across countertops and power outlets.",
    details: [
      { title: "Whole-home music", copy: "Play one source everywhere or give each space independent control without visible clutter." },
      { title: "Outdoor entertainment", copy: "Weather-ready audio and television solutions extend the experience to pools, patios, and lanais." },
      { title: "Clean television design", copy: "Plan mounting, wiring, equipment location, and control before the wall is finished." },
      { title: "Simple operation", copy: "A polished system should be easy for family and guests to use without a stack of remotes." },
    ],
    ideal: ["Indoor-outdoor Florida living", "Media rooms and gathering spaces", "Clean wall-mounted television installations", "Clients who value music throughout the home"],
    // Answers pending Jorge's approval; a question is published only once its answer is filled in.
    faqs: [
      { q: "Can speakers be weatherproof on the lanai?", a: "" },
      { q: "Can each room play something different?", a: "" },
      { q: "Do you hide the equipment?", a: "" },
      { q: "Will my guests be able to use it?", a: "" },
    ],
  },
  networking: {
    path: "/services/networking",
    metaTitle: "Home Network & Wi-Fi Design | Sarasota",
    metaDescription: "Structured wiring, managed Wi-Fi and network segmentation for Sarasota homes with cameras, streaming, remote work and automation.",
    eyebrow: "Professional networking & Wi-Fi",
    title: "The system behind",
    italic: "every other system.",
    intro: "Purpose-built wired and wireless infrastructure for reliable coverage, high device counts, remote work, streaming, cameras, and automation.",
    image: "svc-networking-hero",
    statement: "Smart-home performance begins with a network designed for the property—not a router hidden in one corner.",
    details: [
      { title: "Coverage planning", copy: "Access points are positioned around construction materials, floor plans, outdoor areas, and actual device demand." },
      { title: "Structured wiring", copy: "CAT6 and fiber pathways create a reliable foundation for televisions, cameras, access points, and future systems." },
      { title: "Managed equipment", copy: "Professional gateways, switches, power, and monitoring make the network easier to support and expand." },
      { title: "Secure segmentation", copy: "Separate trusted, guest, camera, and automation traffic when the project requires stronger control." },
    ],
    ideal: ["Large or multi-story homes", "New construction prewire", "Properties with outdoor coverage needs", "Homes with cameras and many connected devices"],
    // Answers pending Jorge's approval; a question is published only once its answer is filled in.
    faqs: [
      { q: "Why is my Wi-Fi bad in the lanai?", a: "" },
      { q: "Do I need wired access points?", a: "" },
      { q: "Can you separate guest and camera networks?", a: "" },
      { q: "Do you work with my ISP's modem?", a: "" },
    ],
  },
  climate: {
    path: "/services/climate",
    metaTitle: "Smart Climate & Energy Control | Sarasota",
    metaDescription: "Scheduling, occupancy and scene-based climate control integrated with lighting and shades for seasonal and year-round Florida homes.",
    eyebrow: "Climate & energy control",
    title: "Comfort that follows",
    italic: "the way you live.",
    intro: "Thoughtful climate control, schedules, occupancy routines, and automation that improve comfort without constant adjustment.",
    image: "svc-climate-hero",
    statement: "Comfort becomes effortless when climate, shades, lighting, and occupancy work from the same plan.",
    details: [
      { title: "Smarter scheduling", copy: "Setbacks and comfort periods can reflect real household routines instead of a rigid weekly timer." },
      { title: "Room awareness", copy: "Use supported sensors and system logic to understand temperature, occupancy, and changing conditions." },
      { title: "Integrated scenes", copy: "Away, sleep, arrival, and vacation modes can coordinate climate with lights, shades, and security." },
      { title: "Remote visibility", copy: "Check and adjust supported systems from anywhere while retaining professional serviceability." },
    ],
    ideal: ["Seasonal Florida residences", "Homes with multiple HVAC zones", "Clients focused on comfort and convenience", "Projects already integrating lighting and shades"],
    // Answers pending Jorge's approval; a question is published only once its answer is filled in.
    faqs: [
      { q: "Which thermostats do you integrate?", a: "" },
      { q: "Can shades and AC work together?", a: "" },
      { q: "Does it help with humidity when we're away?", a: "" },
      { q: "Can I control it remotely?", a: "" },
    ],
  },
  landscape: {
    path: "/services/landscape-lighting",
    metaTitle: "Landscape & Architectural Lighting | Sarasota",
    metaDescription: "Landscape, facade and outdoor living lighting for Sarasota, Bradenton and Venice homes—designed, installed and tied into whole-home lighting control.",
    eyebrow: "Landscape & architectural lighting",
    image: "svc-landscape-hero",
    secondImage: "svc-landscape-pool",
    title: "The home after dark,",
    italic: "designed on purpose.",
    intro: "Facade, landscape, pathway, pool, and lanai lighting planned as one composition—and connected to the same scenes and schedules as the inside of the home.",
    statement: "Outdoor lighting should reveal the architecture and make the property safer to move through—without glare or a runway of path lights.",
    details: [
      { title: "Lighting design", copy: "Fixture locations, beam angles, and color temperature are chosen to highlight the architecture, trees, and plantings that matter." },
      { title: "Outdoor living", copy: "Lanais, pools, docks, and entertaining areas get layered light that is comfortable to sit in, not just bright." },
      { title: "Safe arrival", copy: "Driveways, steps, entries, and pathways are lit so the property is easy to navigate at night." },
      { title: "Integrated control", copy: "Outdoor lighting can follow sunset schedules and join whole-home scenes instead of running on separate timers." },
    ],
    ideal: ["New landscapes and renovations", "Homes with pools, lanais, or docks", "Properties with architectural facades", "Owners replacing failing low-voltage systems"],
    // Answers pending Jorge's approval; a question is published only once its answer is filled in.
    faqs: [
      { q: "Will it work with my existing transformer?", a: "" },
      { q: "How long do LED fixtures last in salt air?", a: "" },
      { q: "Can it follow sunset automatically?", a: "" },
      { q: "Do you light pools and docks?", a: "" },
    ],
  },
  solar: {
    path: "/services/solar-tesla",
    metaTitle: "Tesla Solar, Powerwall & Solar Roof | Sarasota",
    metaDescription: "Tesla solar panels, Solar Roof, Powerwall and Wall Connector installation from All Things Automated Solar, serving Sarasota and the Gulf Coast.",
    eyebrow: "All Things Automated Solar · Tesla Energy",
    image: "svc-solar-hero",
    title: "Your own power,",
    italic: "stored for when you need it.",
    intro: "Tesla solar panels, Solar Roof, Powerwall, and Wall Connector—planned around your roof, your electrical service, and how your home uses energy.",
    statement: "On the Gulf Coast, solar and battery storage are about resilience as much as the electric bill.",
    details: [
      { title: "Solar panels", copy: "Panel layout is planned around roof orientation, shading, and the home's actual energy use." },
      { title: "Solar Roof", copy: "For roof replacements, Tesla Solar Roof combines the roof and the solar array in one system." },
      { title: "Powerwall", copy: "Battery storage keeps essential circuits running during outages and stores solar energy for evening use." },
      { title: "Wall Connector", copy: "Add home EV charging on the same plan, sized to your electrical service." },
    ],
    ideal: ["Homes planning a roof replacement", "Owners who want backup power for storm season", "Households with an EV or planning one", "Properties with good sun exposure"],
    idealHeading: "Planned around the roof, the panel, and the way you use power.",
    phone: teslaPhone,
    // Answers pending Jorge's approval; a question is published only once its answer is filled in.
    faqs: [
      { q: "Does Powerwall run the whole house in an outage?", a: "" },
      { q: "Solar Roof or panels?", a: "" },
      { q: "What about hurricane season?", a: "" },
      { q: "Do you handle permits and FPL interconnection?", a: "" },
    ],
  },
  ev: {
    path: "/services/ev-chargers",
    metaTitle: "EV Charger Installation | Sarasota & Bradenton",
    metaDescription: "Home EV charger installation in Sarasota and Bradenton: hardwired wall chargers or a 240V plug-in outlet, sized to your electrical panel.",
    eyebrow: "EV charger installation",
    image: "svc-ev-hero",
    title: "Charge at home,",
    italic: "the right way.",
    intro: "A hardwired wall charger or a 240V plug-in outlet—installed to fit your vehicle, your garage, and your electrical panel.",
    statement: "A good EV install starts at the electrical panel, not at the charger.",
    details: [
      { title: "Panel check", copy: "We confirm your service and panel capacity before recommending a charger size or circuit." },
      { title: "Hardwired chargers", copy: "Wall-mounted chargers, including the Tesla Wall Connector, for the fastest and cleanest home charging." },
      { title: "240V outlets", copy: "A dedicated plug-in outlet for the mobile charger that came with your vehicle." },
      { title: "Clean placement", copy: "The charger goes where the cable reaches the car comfortably, with tidy conduit and wiring." },
    ],
    ideal: ["New EV owners", "Two-EV households", "Garages that need a dedicated circuit", "Homes adding solar or Powerwall"],
    idealHeading: "Sized to your car, your garage, and your panel.",
    // Answers pending Jorge's approval; a question is published only once its answer is filled in.
    faqs: [
      { q: "Hardwired charger or 240V outlet?", a: "" },
      { q: "Will my panel handle it?", a: "" },
      { q: "How long does an install take?", a: "" },
      { q: "Do you install Tesla Wall Connectors?", a: "" },
    ],
  },
  electrical: {
    path: "/electrical",
    metaTitle: "Electrical Service & Repair | Sarasota",
    metaDescription: "Electrical service and repair in Sarasota, Bradenton and Venice: troubleshooting, new circuits, fixtures, outlets and dedicated lines.",
    eyebrow: "Electrical services · A separate branch",
    image: "electrical-hero",
    title: "Electrical service",
    italic: "and repair.",
    intro: "Alongside our automation work, we handle electrical service calls: troubleshooting, new circuits, fixtures, outlets, and dedicated lines.",
    statement: "Every system we install depends on clean, safe electrical work—so we do that work ourselves.",
    details: [
      { title: "Troubleshooting", copy: "Tripping breakers, dead outlets, flickering lights, and circuits that stopped working." },
      { title: "New circuits", copy: "Dedicated lines for appliances, equipment, workshops, and EV charging." },
      { title: "Fixtures and devices", copy: "Light fixtures, ceiling fans, outlets, switches, and dimmers installed and replaced." },
      { title: "Remodel wiring", copy: "Electrical work for kitchens, baths, and additions, coordinated with any lighting control or low-voltage plans." },
    ],
    ideal: ["Homeowners with an electrical problem", "Remodels and additions", "New appliance or equipment circuits", "Projects pairing electrical with lighting control"],
    idealHeading: "Straightforward electrical work, done carefully.",
    // Answers pending Jorge's approval; a question is published only once its answer is filled in.
    faqs: [
      { q: "Do you do small jobs?", a: "" },
      { q: "Can you come out the same day?", a: "" },
      { q: "Are you licensed and insured?", a: "" },
      { q: "Do you pull permits?", a: "" },
    ],
  },
};

// Order of the systems on the /services index.
export const serviceOrder = ["lighting", "landscape", "automation", "security", "networking", "audio", "climate", "ev", "solar"];

export { articleOrder, articles } from "./articles";
